
ERROR_TIME: 2021-07-24 19:40:32,245
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 521
ERROR_NAME: local variable 'doc' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 511, in run_program
    content = analyze_content(doc,abbr)
UnboundLocalError: local variable 'doc' referenced before assignment
